### ISSUE TITLE
Braces in `else` block do not trigger errors

### ISSUE THREAD

**Issue by SolalPirelli** [simhayoz/eval-code-quality#19]
The detection of problems with `if` braces works great, but `else` doesn't seem to trigger errors, e.g.

```java
class Class {
  void m() {
    if (true) {
      System.out.println("True");
    }
    else // mismatched style with the rest of the class
    {
      System.out.println("False");
    }
  }
}
```

**Comment by simhayoz** [comment]
This does not trigger errors in the current implementation due to the way the tests are done, there is 3 different properties tested separately:

- start bracket: `if(...) {`
- close bracket and child: `} while(...);`
- child in-between brackets: `} else {`

But it does not seems to be the logical way to test opening and closing bracket, I will change it to add the third properties to the two above

**Comment by simhayoz** [comment]
Done in #20
